<form action="/products" method="POST">
    <div class="form-group">
        <label for="name">Product Name</label>
        <input type="text" class="form-control" id="name" name="name" required>
    </div>
    <div class="form-group">
        <label for="price">Product Price</label>
        <input type="text" class="form-control" id="price" name="price" required>
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
</form>