<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>Product Catalog</title>
</head>
<body>
    <header class="bg-light text-white text-center py-3">
        <h1>
            <a href="/">Product Catalog</a>
        </h1>
    </header>
    <div class="container mt-5">